
import React, { useState, useEffect } from 'react';
import { ArrowLeft, ExternalLink, RefreshCw, Database, LogOut, CheckCircle, Search, FileText, AlertTriangle, MessageSquare, Copy } from 'lucide-react';
import { fetchAnalytics, initSupabase, isConfigured } from '../services/loggingService';
import AdminLogin from './AdminLogin';

interface AdminDashboardProps {
  onBack: () => void;
}

const AdminDashboard: React.FC<AdminDashboardProps> = ({ onBack }) => {
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [activeTab, setActiveTab] = useState<'feedback' | 'analytics'>('analytics');
  const [logs, setLogs] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<any>(null);
  const [isConnected, setIsConnected] = useState(isConfigured());
  const [searchTerm, setSearchTerm] = useState('');
  
  // Settings for manual connection (if not hardcoded)
  const [supaUrl, setSupaUrl] = useState('');
  const [supaKey, setSupaKey] = useState('');

  // Selected Log for details view
  const [selectedLog, setSelectedLog] = useState<any | null>(null);

  useEffect(() => {
    const sessionAuth = sessionStorage.getItem('admin_auth');
    if (sessionAuth === 'true') {
      setIsAuthenticated(true);
    }
  }, []);

  const handleLogin = () => {
    setIsAuthenticated(true);
    sessionStorage.setItem('admin_auth', 'true');
  };

  const handleLogout = () => {
    setIsAuthenticated(false);
    sessionStorage.removeItem('admin_auth');
    onBack();
  };

  const loadLogs = async () => {
    setLoading(true);
    setError(null);
    const { data, error: fetchError } = await fetchAnalytics();
    if (fetchError) {
        setError(fetchError);
    } else {
        setLogs(data);
    }
    setLoading(false);
  };

  const handleConnect = () => {
     if(supaUrl && supaKey) {
         initSupabase(supaUrl, supaKey);
         setIsConnected(true);
         loadLogs();
     }
  };

  useEffect(() => {
    if (activeTab === 'analytics' && isAuthenticated) {
        if (isConnected) {
            loadLogs();
        }
    }
  }, [activeTab, isAuthenticated, isConnected]);

  const filteredLogs = logs.filter(log => 
      log.session_id.toLowerCase().includes(searchTerm.toLowerCase()) || 
      (log.product_name && log.product_name.toLowerCase().includes(searchTerm.toLowerCase()))
  );

  const copySQL = () => {
    const sql = `create table session_analytics (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  session_id text not null,
  product_name text,
  scenario_id text,
  proponent_name text,
  opponent_name text,
  model_used text,
  file_count int default 0,
  turn_count int default 0,
  moderator_count int default 0,
  user_interjected boolean default false,
  duration_seconds int default 0,
  viability_score int,
  verdict_summary text,
  full_payload jsonb
);
alter table session_analytics disable row level security;`;
    navigator.clipboard.writeText(sql);
    alert("SQL copied to clipboard! Run this in Supabase SQL Editor.");
  };

  if (!isAuthenticated) {
    return <AdminLogin onLogin={handleLogin} onBack={onBack} />;
  }

  return (
    <div className="min-h-screen bg-natural-100 p-4 md:p-8 flex items-center justify-center w-full">
      <div className="w-full max-w-[95%] bg-white rounded-xl shadow-xl border border-natural-300 p-4 md:p-8 h-[90vh] flex flex-col">
        
        {/* Header */}
        <div className="flex justify-between items-center mb-6 border-b border-natural-200 pb-4 shrink-0">
             <div className="flex items-center gap-4">
                <button onClick={onBack} className="p-2 hover:bg-natural-100 rounded-full transition-colors flex items-center gap-2 text-natural-600">
                  <ArrowLeft size={20}/> <span className="hidden md:inline">Back</span>
                </button>
                <h1 className="text-xl md:text-2xl font-bold text-natural-900">Admin Intelligence</h1>
             </div>
             
             <button 
                onClick={handleLogout}
                className="flex items-center gap-2 text-xs font-medium text-rose-600 hover:text-rose-800 bg-rose-50 px-3 py-2 rounded-lg transition-colors"
             >
                <LogOut size={14} /> Logout
             </button>
        </div>

        {/* Tabs */}
        <div className="flex gap-4 border-b border-natural-300 mb-6 shrink-0">
            <button 
                onClick={() => setActiveTab('analytics')}
                className={`pb-2 px-4 font-medium transition-colors whitespace-nowrap ${activeTab === 'analytics' ? 'text-natural-900 border-b-2 border-natural-900' : 'text-natural-500'}`}
            >
                Session Analytics
            </button>
            <button 
                onClick={() => setActiveTab('feedback')}
                className={`pb-2 px-4 font-medium transition-colors whitespace-nowrap ${activeTab === 'feedback' ? 'text-natural-900 border-b-2 border-natural-900' : 'text-natural-500'}`}
            >
                External Feedback
            </button>
        </div>

        {activeTab === 'feedback' && (
            <div className="flex-1 flex flex-col items-center justify-center animate-fade-in">
                <div className="bg-blue-50 border border-blue-200 rounded-lg p-6 mb-8 max-w-lg mx-auto text-center">
                    <h2 className="text-lg font-bold text-blue-800 mb-2">Feedback System</h2>
                    <p className="text-blue-700 text-sm">
                        User feedback is collected via external Google Forms.
                    </p>
                </div>
                <a 
                    href="https://docs.google.com/forms/d/1Xy_.../edit" 
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex items-center gap-2 bg-natural-900 text-white px-6 py-3 rounded-lg font-bold hover:bg-natural-700 transition-colors shadow-lg"
                >
                    <ExternalLink size={20} />
                    View Responses (Google Forms)
                </a>
            </div>
        )}

        {activeTab === 'analytics' && (
            <div className="flex-1 flex flex-col min-h-0 animate-fade-in">
                
                {/* Connection Check */}
                {!isConnected ? (
                    <div className="bg-natural-50 p-4 rounded-lg border border-natural-200 mb-4 shrink-0">
                        <h3 className="font-bold text-sm mb-2 flex items-center gap-2">
                            <Database size={16}/> Connect to Supabase
                        </h3>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-3">
                            <input type="text" placeholder="URL" value={supaUrl} onChange={(e) => setSupaUrl(e.target.value)} className="border px-2 py-1 rounded text-sm"/>
                            <input type="password" placeholder="Key" value={supaKey} onChange={(e) => setSupaKey(e.target.value)} className="border px-2 py-1 rounded text-sm"/>
                        </div>
                        <button onClick={handleConnect} className="bg-natural-800 text-white text-xs px-3 py-2 rounded">Connect</button>
                    </div>
                ) : (
                    <>
                        {/* Error Display - TABLE MISSING */}
                        {error && (error.code === '42P01' || error.message?.includes('does not exist')) && (
                            <div className="bg-rose-50 border border-rose-200 rounded-lg p-6 mb-6 shrink-0">
                                <h3 className="text-lg font-bold text-rose-800 mb-2 flex items-center gap-2">
                                    <AlertTriangle /> Database Table Missing
                                </h3>
                                <p className="text-rose-700 text-sm mb-4">
                                    The "session_analytics" table does not exist in your Supabase project. You must run this SQL query in your Supabase SQL Editor.
                                </p>
                                <div className="bg-rose-100 p-3 rounded border border-rose-200 font-mono text-xs overflow-x-auto mb-3">
                                    <pre>{`create table session_analytics (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  session_id text not null,
  product_name text,
  scenario_id text,
  proponent_name text,
  opponent_name text,
  model_used text,
  file_count int default 0,
  turn_count int default 0,
  moderator_count int default 0,
  user_interjected boolean default false,
  duration_seconds int default 0,
  viability_score int,
  verdict_summary text,
  full_payload jsonb
);

alter table session_analytics disable row level security;`}</pre>
                                </div>
                                <button onClick={copySQL} className="flex items-center gap-2 bg-rose-600 text-white px-4 py-2 rounded-lg text-sm font-bold hover:bg-rose-700">
                                    <Copy size={16} /> Copy SQL to Clipboard
                                </button>
                            </div>
                        )}

                        {/* Toolbar */}
                        <div className="flex justify-between items-center mb-4 shrink-0">
                            <div className="relative">
                                <Search className="absolute left-3 top-2.5 text-natural-400" size={16} />
                                <input 
                                    type="text" 
                                    placeholder="Filter by Session ID or Product..." 
                                    value={searchTerm}
                                    onChange={(e) => setSearchTerm(e.target.value)}
                                    className="pl-9 pr-4 py-2 border border-natural-300 rounded-lg text-sm w-64 focus:ring-1 focus:ring-natural-500 outline-none"
                                />
                            </div>
                            <button onClick={loadLogs} className="flex items-center gap-2 text-natural-600 hover:bg-natural-100 px-3 py-2 rounded-lg text-sm transition-colors">
                                <RefreshCw size={16} className={loading ? "animate-spin" : ""} /> Refresh
                            </button>
                        </div>

                        {/* DATA TABLE */}
                        <div className="flex-1 border border-natural-300 rounded-lg overflow-hidden bg-white shadow-sm overflow-auto">
                            <table className="w-full text-sm text-left border-collapse">
                                <thead className="bg-natural-100 text-natural-700 font-semibold border-b border-natural-300 sticky top-0 z-10">
                                    <tr>
                                        <th className="p-3 border-r border-natural-200">Date / ID</th>
                                        <th className="p-3 border-r border-natural-200">Product / Scenario</th>
                                        <th className="p-3 border-r border-natural-200 w-32">Score</th>
                                        <th className="p-3 border-r border-natural-200">Stats</th>
                                        <th className="p-3 border-r border-natural-200">Opponent</th>
                                        <th className="p-3 text-center">Actions</th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y divide-natural-200">
                                    {filteredLogs.length > 0 ? filteredLogs.map((log) => (
                                        <tr key={log.id} className="hover:bg-natural-50 transition-colors">
                                            {/* ID & Time */}
                                            <td className="p-3 border-r border-natural-100 align-top">
                                                <div className="font-mono text-xs text-natural-500">{new Date(log.created_at).toLocaleDateString()}</div>
                                                <div className="font-mono text-xs text-natural-400 mb-1">{new Date(log.created_at).toLocaleTimeString()}</div>
                                                <div 
                                                    className="font-mono text-[10px] bg-natural-100 px-1 py-0.5 rounded inline-block text-natural-600 cursor-pointer hover:bg-natural-200"
                                                    onClick={() => {navigator.clipboard.writeText(log.session_id); alert('ID Copied');}}
                                                    title={log.session_id}
                                                >
                                                    {log.session_id.substring(0, 8)}...
                                                </div>
                                            </td>

                                            {/* Context */}
                                            <td className="p-3 border-r border-natural-100 align-top">
                                                <div className="font-bold text-natural-800 line-clamp-2">{log.product_name || "Untitled"}</div>
                                                <div className="text-xs text-natural-500 flex items-center gap-1 mt-1">
                                                    <span className="bg-natural-100 px-1.5 py-0.5 rounded">{log.scenario_id}</span>
                                                    {log.file_count > 0 && <span className="flex items-center gap-0.5 text-blue-600"><FileText size={10}/> {log.file_count}</span>}
                                                </div>
                                            </td>

                                            {/* Score */}
                                            <td className="p-3 border-r border-natural-100 align-top">
                                                <div className={`text-lg font-bold ${
                                                    log.viability_score >= 80 ? 'text-emerald-600' : 
                                                    log.viability_score >= 50 ? 'text-yellow-600' : 'text-rose-600'
                                                }`}>
                                                    {log.viability_score ?? 'N/A'}%
                                                </div>
                                                <div className="text-[10px] text-natural-400">Viability</div>
                                            </td>

                                            {/* Stats */}
                                            <td className="p-3 border-r border-natural-100 align-top">
                                                <div className="text-xs space-y-1">
                                                    <div className="flex justify-between gap-2"><span>Duration:</span> <span className="font-mono">{log.duration_seconds}s</span></div>
                                                    <div className="flex justify-between gap-2"><span>Turns:</span> <span className="font-mono">{log.turn_count}</span></div>
                                                    <div className="flex justify-between gap-2"><span>Mods:</span> <span className="font-mono text-amber-600">{log.moderator_count}</span></div>
                                                    {log.user_interjected && <div className="text-blue-600 font-bold text-[10px] flex items-center gap-1"><MessageSquare size={10}/> Interjected</div>}
                                                </div>
                                            </td>

                                            {/* Opponent */}
                                            <td className="p-3 border-r border-natural-100 align-top">
                                                <div className="text-sm text-natural-700">{log.opponent_name}</div>
                                                <div className="text-[10px] text-natural-400 mt-1">{log.model_used}</div>
                                            </td>

                                            {/* Action */}
                                            <td className="p-3 align-top text-center">
                                                <button 
                                                    onClick={() => setSelectedLog(log)}
                                                    className="bg-natural-800 text-white text-xs px-3 py-1.5 rounded hover:bg-natural-700 transition-colors shadow-sm"
                                                >
                                                    Details
                                                </button>
                                            </td>
                                        </tr>
                                    )) : (
                                        <tr>
                                            <td colSpan={6} className="p-8 text-center text-natural-400 italic">
                                                {!error && "No sessions recorded yet. Run a simulation to see analytics."}
                                                {error && <span className="text-rose-500">Error loading logs. See above.</span>}
                                            </td>
                                        </tr>
                                    )}
                                </tbody>
                            </table>
                        </div>
                    </>
                )}
            </div>
        )}

        {/* DETAILS MODAL */}
        {selectedLog && (
            <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4 backdrop-blur-sm">
                <div className="bg-white w-full max-w-2xl max-h-[85vh] rounded-xl shadow-2xl flex flex-col overflow-hidden">
                    <div className="bg-natural-100 p-4 border-b border-natural-300 flex justify-between items-center">
                        <div>
                            <h3 className="font-bold text-natural-800">Session Details</h3>
                            <span className="text-xs font-mono text-natural-500">{selectedLog.session_id}</span>
                        </div>
                        <button onClick={() => setSelectedLog(null)} className="p-1 hover:bg-natural-200 rounded"><LogOut size={16} className="rotate-180"/></button>
                    </div>
                    <div className="p-6 overflow-y-auto space-y-6">
                        
                        <div>
                            <h4 className="text-xs font-bold text-natural-500 uppercase tracking-wide mb-2">Prompt / Context</h4>
                            <div className="bg-natural-50 p-3 rounded-lg text-sm text-natural-800 border border-natural-200 whitespace-pre-wrap">
                                {selectedLog.full_payload?.prompt || selectedLog.product_name}
                            </div>
                        </div>

                        <div>
                            <h4 className="text-xs font-bold text-natural-500 uppercase tracking-wide mb-2">Verdict Summary</h4>
                            <p className="text-sm text-natural-700 leading-relaxed">
                                {selectedLog.verdict_summary}
                            </p>
                        </div>

                        <div>
                             <h4 className="text-xs font-bold text-natural-500 uppercase tracking-wide mb-2">Transcript Preview</h4>
                             <div className="space-y-2">
                                {selectedLog.full_payload?.messages?.slice(0, 3).map((m: any, i: number) => (
                                    <div key={i} className="text-xs border-l-2 border-natural-300 pl-2">
                                        <span className="font-bold">{m.role}:</span> {m.content.substring(0, 100)}...
                                    </div>
                                ))}
                                <div className="text-xs text-center text-natural-400 italic">... {selectedLog.turn_count} total messages</div>
                             </div>
                        </div>

                    </div>
                    <div className="p-4 bg-natural-50 border-t border-natural-200 text-right">
                        <button onClick={() => setSelectedLog(null)} className="px-4 py-2 bg-natural-200 hover:bg-natural-300 rounded text-sm font-medium">Close</button>
                    </div>
                </div>
            </div>
        )}

      </div>
    </div>
  );
};

export default AdminDashboard;
